apiVersion: federation.maistra.io/v1
kind: ImportedServiceSet
metadata:
  name: stage-mesh
  namespace: prod-mesh
spec:
  importRules:
    - importAsLocal: true
      nameSelector:
        alias:
          name: details
          namespace: prod-bookinfo
        name: details
        namespace: stage-bookinfo
      type: NameSelector
    - importAsLocal: true
      nameSelector:
        alias:
          name: reviews
          namespace: prod-bookinfo
        name: reviews
        namespace: stage-bookinfo
      type: NameSelector
