kind: VirtualService
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: details
  namespace: prod-bookinfo
spec:
  hosts:
    - details
  http:
    - mirror:
        host: details
      route:
        - destination:
            host: details
